a

diff --git a/dpizhid b/dpizhid
--- a/dpizhid
+++ b/dpizhid
@@ -1,14 +1,15 @@
 #!/bin/sh
+### My password helper script
 
 CURL="curl --connect-timeout 5"
 DMENU="dmenu -i -l 5"
 remote="http://10.77.77.77"
 
-login_cmd="$CURL $remote/cgi/login"
+login_cmd="$CURL $remote/api/login.php"
 
 ## Login Funtion ##
-if [ -z "$($login_cmd)" ]; then
-  if [ "$($login_cmd -d "$(dmenu -nf '#000000' -nb '#000000' -p 'PIZ_HID Login:' <&-)")" = "authenticated" ]; then
+if [ "$($login_cmd)" = "failure" ]; then
+  if [ "$($login_cmd -X POST -F "password=$(dmenu -nf '#000000' -nb '#000000' -p 'PIZ_HID Login:' <&-)")" = "authenticated" ]; then
     notify-send "DPIZHID" "Piz_Hid authenticated" &
   else
     notify-send "DPIZHID" "Piz_Hid authentication failed" &
@@ -18,26 +19,34 @@ if [ -z "$($login_cmd)" ]; then
 fi
 
 ## PIZ_HID Communication ##
-entry_list="$($CURL $remote/cgi/vault)"
+entry_list="$($CURL $remote/api/list.php)"
 entry_sel="$(printf "%s\n---Lock---\n---Shutdown---\n---Multiline---\n---ClipPass---" "$entry_list" |
   $DMENU -p "Entry:")" || exit
 
 ## PIZ_HID Data Processing ##
-if [ "$entry_sel" = "---Lock---" ]; then
-  $CURL $remote/cgi/lock
-elif [ "$entry_sel" = "---Shutdown---" ]; then
-  $CURL $remote/cgi/shutdown
-elif [ "$entry_sel" = "---Multiline---" ]; then
+case "$entry_sel" in
+"---Lock---")
+  $CURL "$remote/api/logout.php"
+  ;;
+"---Shutdown---")
+  $CURL "$remote/api/shutdown.php"
+  ;;
+"---Multiline---")
   ## list non-passwd info in entry and clip it ##
   entry_sel="$(printf "%s" "$entry_list" | $DMENU -p "Multiline:")" || exit
-  entry_contents="$($CURL -d "$entry_sel" $remote/cgi/vault-multi | $DMENU -p "Multiline:")" || exit
+  entry_contents="$($CURL "$remote/api/multiline.php?entry=$entry_sel" |
+    $DMENU -p "Multiline:")" || exit
 
   [ "$entry_contents" ] && printf "%s" "$entry_contents" | xclip -selection clipboard
-elif [ "$entry_sel" = "---ClipPass---" ]; then
+  ;;
+"---ClipPass---")
   ## insert pass into clipboard ##
-  entry_sel="$(printf "%s" "$entry_list" | $DMENU -p "Entry:")" || exit
-  $CURL -d "$entry_sel" $remote/cgi/vault-raw | xclip -selection clipboard && notify-send "DPIZHID" "ClipPass" &
-else
-  ## autowrite pass and clip user ##
-  $CURL -d "$entry_sel" $remote/cgi/vault | xclip -selection clipboard
-fi
+  entry_sel="$(printf "%s" "$entry_list" | $DMENU -p "ClipPass:")" || exit
+  $CURL "$remote/api/password.php?entry=${entry_sel}&clip"  | xclip -selection clipboard &&
+    notify-send "DPIZHID" "ClipPass" &
+  ;;
+*)
+  ## auto-write pass and clip user ##
+  $CURL "$remote/api/password.php?entry=${entry_sel}"  | xclip -selection clipboard
+  ;;
+esac
